### PR TITLE
The Spring-Context configuration supports environment variables

### PR DESCRIPTION
**Pull request by fantasy1713**

### CODE REVIEW

**Comment by olaf-otto** [comment]
Dear @fantasy1713,

Thanks a lot for your contribution! Could you please provide some context on this change:

- Is this a feature contained in standard Spring missing from gemini-blueprint?
- Do you have a specific use-case at hand? 

I assume this change could be used to achieve something similar to https://www.baeldung.com/spring-profiles, is this the intention?

Kind regards,
Olaf

**Comment by fantasy1713** [comment]
邮件丢失……                                                                       骗你的

**Comment by fantasy1713** [comment]
Dear Olaf
	Thanks a lot for your reply.
	In my case, the Sprint-Context location in MANIFEST.MF is like this: Spring-Context: *,${CONFIG_DIR}/global.datasource.xml
	We need to load application context xml file from the outside of the bundle jar file, just like ${SERVICE_INSTALL_PATH}/etc/global.datasource.xml
	Because the configuration path is variable, we need to use environment variables to specify the path.

Kind regards,
fantasy1713

**Comment by olaf-otto** [comment]
Dear @fantasy1713 

The option to import XML from external locations and use placeholders in the resolution is already supported in the spring context (https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-factory-xml-import).

For instance, your OSGI-INF/blueprint/context.xml may contain:

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans" ...>

...
    <import resource="file:${datasource.context.location}" />
...
</beans>

```

Here, "datasource.context.location" would be a system property pointing to an arbitrary path.

Would this solve your requirement?

Kind regards,
Olaf

**Comment by olaf-otto** [comment]
Closing as won't fix - please re-open if the solution posted above does not cover your needs.

**Comment by fantasy1713** [comment]
Dear @olaf-otto 
We recently discovered that upgrading spring to version 5.3.27 is incompatible with the current gemini-Blueprint. The reason is that spring adds a condition judgment on Classloader. 
 [https://github.com/spring-projects/spring-framework/commit/0c80e5f9e6afeca3447caac1449a45fa1fa03ea0](https://github.com/spring-projects/spring-framework/commit/0c80e5f9e6afeca3447caac1449a45fa1fa03ea0)

BundleDelegatingClassLoader does not have a parent. As a result, classes in other bundles cannot be loaded.
The program throws an exception:
java.lang.IllegalArgumentException: interface  xxxxx   is not visible from class loader

I hope that a new version of gemini-blueprint can adapt to spring's modification.

Kind regards,
fantasy1713

**Comment by olaf-otto** [comment]
Hi @fantasy1713 

Thanks for mentioning this - indeed a new release i overdue. I hope to be able to provide one soon.

Kind regards,
Olaf

**Comment by fantasy1713** [comment]
邮件丢失……                                                                       骗你的

**Pull request closed without merging**
