### PR TITLE
ATLASSIAN upgrade to Spring 6

### PR DESCRIPTION
**Pull request by martokarski**
Hi, I'm Atlassian developer. We are using Gemini and I we would like to understand what is the future of this project. There is no update since 2018, however I see some PRs created in the last year.

We are mostly interested in integration with Spring 6. However, knowledge about general plans for this repository would be really helpful too.

Thank you in advance!

Marek Tokarski
Senior Software Engineer at Atlassian

### CODE REVIEW

**Comment by martokarski** [comment]
@olaf-otto it seems you are responsible for this project. Can you share the details?

**Comment by olaf-otto** [comment]
> @olaf-otto it seems you are responsible for this project. Can you share the details?

Dear @martokarski, thanks for reaching our and great to hear you are using gemini blueprint.

I am indeed the project lead. The project has been on maintenance mode for the last years, mostly owing to the fact that I am it's sole contributor at this point and lack the time to actively develop it. It also isn't quite easy to contribute, since eclipse has legal procedures in place to ensure IP cleanliness, which in the past has driven away potential contributors.

That being said, I would love to see some activity and an upgrade to Spring 6. Here, I foresee upgrading to the a Java 17+ baseline as the biggest challenge. We have a large and valuable, but legacy test code base that is all but easy to comprehend. I shall reach out via the project's mailing list to find potential supporters for this undertaking.

For now, let's see what happens when I upgrade to Spring 6 on a feature branch.

Kind regards,
Olaf

**Comment by olaf-otto** [comment]
@martokarski new PR: https://github.com/eclipse-gemini/gemini.blueprint/pull/10

**Comment by martokarski** [comment]
@olaf-otto thank you for the fast and honest response! 

We will need to analyse that topic internally and perhaps make some actions on our side.

**Comment by olaf-otto** [comment]
Hi @martokarski 

I have reached out via the gemini blueprint mailing list. @fwaibel is a core contributer to gemini-blueprint and would be interested in a joint effort for the migration - if you are interested, please feel free to contact him directly!

Kind regards,
Olaf

**Comment by fwaibel** [comment]
Hi @martokarski,
please let me know if you need some input from my side.
This seems like a good opportunity for get the ball rolling again...
Regards,
  florian

**Comment by jacquipre** [comment]
Hi, 
we are also interested in a Spring 6 update of the Gemini project (which we are using) since we are just updating all our products to Spring 6. 
Regards, jacquipre

**Comment by mtokarski-atlassian** [comment]
hi @olaf-otto,

Sorry for my lack of response in the past months. Do you have any update on the upgrade to Spring 6? I see no recent activity in the PR you mentioned earlier (https://github.com/eclipse-gemini/gemini.blueprint/pull/10). Recently I also found out that another PR was closed without merging - https://github.com/eclipse-gemini/gemini.blueprint/pull/15.

**Pull request closed without merging**
